package bookshop.code;
// Generated 15.04.2016 15:53:53 by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer", catalog = "bookshop")
public class Customer implements java.io.Serializable
{

	private Integer id;
	private String FName;
	private String LName;
	private String MName;
	private Integer admin;
	private String email;
	private String password;
	private String contactNumber;
	private String address;
	private Set<Orders> orderses = new HashSet<Orders>(0);

	public Customer()
	{
	}

	public Customer(String FName, String LName, String MName, String email, String contactNumber, String address,
			Set<Orders> orderses)
	{
		this.FName = FName;
		this.LName = LName;
		this.MName = MName;
		this.email = email;
		this.contactNumber = contactNumber;
		this.address = address;
		this.orderses = orderses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@Column(name = "f_name", length = 40)
	public String getFName()
	{
		return this.FName;
	}

	public void setFName(String FName)
	{
		this.FName = FName;
	}

	@Column(name = "l_name", length = 40)
	public String getLName()
	{
		return this.LName;
	}

	public void setLName(String LName)
	{
		this.LName = LName;
	}

	@Column(name = "m_name", length = 40)
	public String getMName()
	{
		return this.MName;
	}

	public void setMName(String MName)
	{
		this.MName = MName;
	}

	@Column(name = "admin", nullable = false, columnDefinition = "int default 0")
	public Integer getAdmin()
	{
		return this.admin;
	}

	public void setAdmin(Integer admin)
	{
		this.admin = admin;
	}

	@Column(name = "email", length = 40)
	public String getEmail()
	{
		return this.email;
	}

	public void setEmail(String email)
	{
		this.email = email;
	}

	@Column(name = "password", length = 20)
	public String getPassword()
	{
		return this.password;
	}

	public void setPassword(String password)
	{
		this.password = password;
	}

	@Column(name = "contact_number", length = 12)
	public String getContactNumber()
	{
		return this.contactNumber;
	}

	public void setContactNumber(String contactNumber)
	{
		this.contactNumber = contactNumber;
	}

	@Column(name = "address", length = 100)
	public String getAddress()
	{
		return this.address;
	}

	public void setAddress(String address)
	{
		this.address = address;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "customer")
	public Set<Orders> getOrderses()
	{
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses)
	{
		this.orderses = orderses;
	}

}
