package bookshop.code;
// Generated 15.04.2016 15:53:53 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name = "orders", catalog = "bookshop")
public class Orders implements java.io.Serializable
{

	private Integer id;
	private Customer customer;
	private ShippingMethod shippingMethod;
	private String status;
	private Date dateTime;
	private String comment;
	private String shippingAddress;
	private Set<OrderItems> orderItemses = new HashSet<OrderItems>(0);

	public Orders()
	{
	}

	public Orders(Customer customer, ShippingMethod shippingMethod, String status, Date dateTime, String comment,
			String shippingAddress, Set<OrderItems> orderItemses)
	{
		this.customer = customer;
		this.shippingMethod = shippingMethod;
		this.status = status;
		this.dateTime = dateTime;
		this.comment = comment;
		this.shippingAddress = shippingAddress;
		this.orderItemses = orderItemses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "customer_id")
	public Customer getCustomer()
	{
		return this.customer;
	}

	public void setCustomer(Customer customer)
	{
		this.customer = customer;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "shipping_method")
	public ShippingMethod getShippingMethod()
	{
		return this.shippingMethod;
	}

	public void setShippingMethod(ShippingMethod shippingMethod)
	{
		this.shippingMethod = shippingMethod;
	}

	@Column(name = "status", length = 40)
	public String getStatus()
	{
		return this.status;
	}

	public void setStatus(String status)
	{
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_time", length = 10)
	public Date getDateTime()
	{
		return this.dateTime;
	}

	public void setDateTime(Date dateTime)
	{
		this.dateTime = dateTime;
	}

	@Column(name = "comment", length = 100)
	public String getComment()
	{
		return this.comment;
	}

	public void setComment(String comment)
	{
		this.comment = comment;
	}

	@Column(name = "shipping_address", length = 100)
	public String getShippingAddress()
	{
		return this.shippingAddress;
	}

	public void setShippingAddress(String shippingAddress)
	{
		this.shippingAddress = shippingAddress;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "orders")
	public Set<OrderItems> getOrderItemses()
	{
		return this.orderItemses;
	}

	public void setOrderItemses(Set<OrderItems> orderItemses)
	{
		this.orderItemses = orderItemses;
	}

}
