package bookshop.code;
// Generated 15.04.2016 15:53:53 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OrderItems generated by hbm2java
 */
@Entity
@Table(name = "order_items", catalog = "bookshop")
public class OrderItems implements java.io.Serializable
{

	private Integer id;
	private Book book;
	private Orders orders;
	private Integer amount;

	public OrderItems()
	{
	}

	public OrderItems(Book book, Orders orders, Integer amount)
	{
		this.book = book;
		this.orders = orders;
		this.amount = amount;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "book_id")
	public Book getBook()
	{
		return this.book;
	}

	public void setBook(Book book)
	{
		this.book = book;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "order_id")
	public Orders getOrders()
	{
		return this.orders;
	}

	public void setOrders(Orders orders)
	{
		this.orders = orders;
	}

	@Column(name = "amount")
	public Integer getAmount()
	{
		return this.amount;
	}

	public void setAmount(Integer amount)
	{
		this.amount = amount;
	}

}
