package bookshop.code;
// Generated 15.04.2016 15:53:53 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ShippingMethod generated by hbm2java
 */
@Entity
@Table(name = "shipping_method", catalog = "bookshop")
public class ShippingMethod implements java.io.Serializable
{

	private Integer id;
	private String name;
	private Integer price;
	private Set<Orders> orderses = new HashSet<Orders>(0);

	public ShippingMethod()
	{
	}

	public ShippingMethod(String name, Integer price, Set<Orders> orderses)
	{
		this.name = name;
		this.price = price;
		this.orderses = orderses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId()
	{
		return this.id;
	}

	public void setId(Integer id)
	{
		this.id = id;
	}

	@Column(name = "name", length = 50)
	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	@Column(name = "price")
	public Integer getPrice()
	{
		return this.price;
	}

	public void setPrice(Integer price)
	{
		this.price = price;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "shippingMethod")
	public Set<Orders> getOrderses()
	{
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses)
	{
		this.orderses = orderses;
	}

}
